### ISSUE TITLE
Improve website performance

### ISSUE THREAD

**Issue by fernandonevarez** [mhmarina/marina-website#1]
Your [gallery](https://github.com/mhmarina/marina-website/blob/main/src/Components/Gallery.tsx) component is currently loading images using the HTML IMG tag. When working with Vite, I recommend utilizing this [library](https://github.com/FatehAK/vite-plugin-image-optimizer) to help improve image loading. You can watch [this](https://www.youtube.com/watch?v=4vJCRYBXRxw) video how to use it in your project. Additionally, ensure that all images in your project are in [WebP format](https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images/?utm_source=lighthouse&utm_medium=devtools) for better performance.

Moreover, it's important to include `alt` tags for every image to enhance SEO. Furthermore, consider adding a [meta description](https://developer.chrome.com/docs/lighthouse/seo/meta-description/?utm_source=lighthouse&utm_medium=devtools) to your website for better search engine optimization.

<img width="851" alt="Screenshot 2024-01-19 at 12 04 47 AM" src="https://github.com/mhmarina/marina-website/assets/69279785/39bb5d9c-28cc-4613-b155-4dc1387c071e">

**Comment by mhmarina** [comment]
just optimized by 83% ^^
